language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

dist: xenial

env:
  global:
    - COMPOSER_ROOT_VERSION=1.3

before_install:
  - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{,.disabled} || echo "xdebug not available"

install: composer install --no-ansi --no-interaction --no-progress --prefer-dist

script: vendor/bin/phpunit