language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

dist: xenial

env:
  global:
    - COMPOSER_ROOT_VERSION=1.3

before_install: composer self-update --2

install:
    - rm composer.lock
    - travis_retry composer update --no-interaction --prefer-dist

script: ./vendor/bin/phpunit --exclude-group performance